# Generated by Django 5.0.4 on 2024-07-27 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idrecon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='Contact',
        ),
    ]
